version: '3'
services:
  soup:
    image: knsk96/soupreporestaurant:latest
     ports:
       - "80:80"
     deploy:
        replicas: 3

  starters:
    image: knsk96/startersreporestaurant:latest
    ports:
      - "81:80"
    deploy:
       replicas: 3


  biryani:
    image: knsk96/biryanireporestaurant:latest
    ports:
      - "82:80"
    deploy:
       replicas: 3

  sweet:
     image: knsk96/sweetreporestaurant:latest
     ports:
       - "83:80"
     deploy:
         replicas: 3


